<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.0.0-beta.1</Version>
    <PackageId>Azure.Messaging.WebPubSub.Client.Protobuf</PackageId>
    <Description>Client Protobuf Protocol for Azure WebPubSub</Description>
    <PackageTags>azure;webpubsub.client</PackageTags>
    <NoWarn>$(NoWarn);0067</NoWarn>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Threading.Channels" Version="10.0.12" />
    <PackageReference Include="Azure.Messaging.WebPubSub.Client" Version="1.0.0"/>
    <PackageReference Include="Google.Protobuf" Version="3.36.1" />
    <PackageReference Include="Grpc.Tools" Version="2.83.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <Protobuf Include="..\..\..\..\..\protocols\protobuf.webpubsub.azure.v1\webpubsub.v1.proto"
              ProtoRoot="..\..\..\..\..\protocols\protobuf.webpubsub.azure.v1"
              Link="Protos\webpubsub.v1.proto"
              GrpcServices="None" />
  </ItemGroup>
</Project>
