version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps

  - package-ecosystem: npm
    directories:
      - "**/*"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    cooldown:
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      npm-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps

  - package-ecosystem: pip
    directories:
      - "**/*"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    cooldown:
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      pip-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps

  - package-ecosystem: maven
    directories:
      - "**/*"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    cooldown:
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      maven-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps

  - package-ecosystem: gomod
    directories:
      - "**/*"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      gomod-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps

  - package-ecosystem: nuget
    directories:
      - "**/*"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    cooldown:
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      nuget-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps

  - package-ecosystem: docker
    directories:
      - "**/*"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      docker-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps
