import rollup from "rollup";
import nodeResolve from "rollup-plugin-node-resolve";
import sourcemaps from "rollup-plugin-sourcemaps";

/**
 * @type {rollup.RollupFileOptions}
 */
const config = {
  input: [
    "./esm/webPubSubServiceRestClient.js",
  ],
  external: [
    "@azure/ms-rest-js",
    "jsonwebtoken",
    "@azure/ms-rest-azure-js",
  ],
  output: {
    file: "./dist/webpubsub.js",
    format: "umd",
    name: "Azure.WebPubSub",
    sourcemap: true,
    globals: {
      "@azure/ms-rest-js": "msRest",
      "@azure/ms-rest-azure-js": "msRestAzure",
      "jsonwebtoken": "jwt",
      "url": "URL",
    },
    banner: `/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */`
  },
  plugins: [
    nodeResolve({ mainFields: ['module', 'main'] }),
    sourcemaps()
  ]
};

export default config;
