/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        NotificationType: "NewMessage" | "NewRoom" | "UpdateMessage" | "AddContact";
        Notification: {
            NotificationType: components["schemas"]["NotificationType"];
            Body: components["schemas"]["NewMessageNotificationBody"] | components["schemas"]["NewRoomNotificationBody"] | components["schemas"]["UpdateMessageNotificationBody"] | components["schemas"]["AddContactNotificationBody"];
        };
        NewMessageNotificationBody: {
            Conversation: components["schemas"]["ChatConversation"];
            Message: components["schemas"]["MessageInfo"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            NotificationType: "NewMessage";
        };
        NewMessageNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            NotificationType?: "NewMessage";
        };
        NewRoomNotificationBody: {
            RoomId: string;
            Title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            NotificationType: "NewRoom";
        };
        NewRoomNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            NotificationType?: "NewRoom";
            Body?: components["schemas"]["NewRoomNotificationBody"];
        };
        UpdateMessageNotificationBody: {
            Conversation: components["schemas"]["ChatConversation"];
            Message: components["schemas"]["MessageInfo"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            NotificationType: "UpdateMessage";
        };
        UpdateMessageNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            NotificationType?: "UpdateMessage";
            Body?: components["schemas"]["UpdateMessageNotificationBody"];
        };
        AddContactNotificationBody: {
            UserId: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            NotificationType: "AddContact";
        };
        AddContactNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            NotificationType?: "AddContact";
            Body?: components["schemas"]["AddContactNotificationBody"];
        };
        UserProfile: {
            /**
             * @description Unique identifier for the user
             * @example user123
             */
            UserId: string;
            /**
             * @description Array of room IDs the user is in
             * @example [
             *       "room1",
             *       "room2",
             *       "room3"
             *     ]
             */
            Rooms: string[];
        };
        ListUserConversationRequest: {
            ContinuationToken?: string | null;
            /** @default 1000 */
            MaxCount: number | null;
        };
        ListUserConversationResponse: {
            Conversations: components["schemas"]["ChatConversation"][];
            ContinuationToken?: string | null;
        };
        ChatConversation: {
            RoomId?: string | null;
            /** @description null for now */
            TopicId?: string | null;
            ConversationId?: string | null;
        };
        /** @enum {string} */
        ApprovalEnum: "AutoApprove" | "ManualApprove" | "AutoDeny";
        UserPolicy: {
            AddContact: components["schemas"]["ApprovalEnum"];
            /**
             * @example [
             *       "Nickname"
             *     ]
             */
            PublicProperties?: string[];
            FriendProperties?: string[];
            PrivateProperties?: string[];
        };
        /** @enum {string} */
        ContactResultState: "OK" | "Pending" | "Failed";
        AddContactResult: {
            UserId: string;
            State: components["schemas"]["ContactResultState"];
            Message: string;
        };
        ContactRequest: {
            UserId: string;
            Message: string;
        };
        /** @enum {string} */
        ContactOperation: "Approve" | "Deny" | "Block";
        ContactRequestOperation: {
            Operation: components["schemas"]["ContactOperation"];
            UserId: string;
        };
        RoomInfo: {
            RoomId: string;
            Title: string;
            DefaultConversation: string;
            /** @description null for now */
            Properties?: Record<string, never> | null;
        };
        /** @enum {string} */
        RoomMemberJoinEnum: "AutoApprove" | "ManualApprove" | "InviteOnly";
        /** @enum {string} */
        RoomMessagePermissionEnum: "Allow" | "AdminOnly" | "Deny";
        /** @enum {string} */
        RoomReactPermissionEnum: "Allow" | "Deny";
        RoomPolicy: {
            MemberJoin: components["schemas"]["RoomMemberJoinEnum"];
            "MessageType.Text"?: components["schemas"]["RoomMessagePermissionEnum"];
            "MessageType.Image"?: components["schemas"]["RoomMessagePermissionEnum"];
            React?: components["schemas"]["RoomReactPermissionEnum"];
        };
        MessageRangeQuery: {
            Conversation: components["schemas"]["ChatConversation"];
            /** @description MessageId */
            Start?: string | null;
            /** @description MessageId */
            End?: string | null;
            /** @default 100 */
            MaxCount: number | null;
        };
        MessageInfo: {
            MessageId: string;
            /** @description UserId */
            Sender: string;
            /** Format: date-time */
            SentAt: string;
            /** @example Join/Leave/Text/Emoji/File/Image/Voice/... */
            MessageType: string;
            /** @example Inline/Reference/External/... */
            MessageBodyType: string;
            Body: string;
            RefMessageId?: string | null;
        };
        CreateTextMessage: {
            Conversation: components["schemas"]["ChatConversation"];
            Message: string;
            RefMessageId?: string | null;
            /** @description Array of UserId */
            "Ext.Mentions"?: string[] | null;
            "Ext.DeleteAfterRead"?: boolean | null;
            /** Format: date-time */
            "Ext.Scheduled"?: string | null;
        };
        CreateMessage: {
            Conversation: components["schemas"]["ChatConversation"];
            /** @example Text/Emoji/File/Image/Voice/... */
            MessageType: string;
            /** Format: binary */
            Body: string;
            RefMessageId?: string | null;
            /** @description Array of UserId */
            "Ext.Mentions"?: string[] | null;
            "Ext.DeleteAfterRead"?: boolean | null;
            /** Format: date-time */
            "Ext.Scheduled"?: string | null;
        };
        MessageBody: {
            Conversation: components["schemas"]["ChatConversation"];
            MessageId: string;
            /** @example Join/Leave/Text/Emoji/File/Image/Voice/... */
            MessageType: string;
            /** @example Inline/Reference/External/... */
            MessageBodyType: string;
            /** Format: binary */
            Body: string;
            RefMessageId?: string | null;
        };
        /** @enum {string} */
        JoinRoomState: "OK" | "Pending" | "Failed";
        JoinRoomResult: {
            /** @description RoomId */
            Room: string;
            State: components["schemas"]["JoinRoomState"];
            Message: string;
        };
        JoinRoomRequest: {
            UserId: string;
            Message: string;
        };
        /** @enum {string} */
        JoinRoomOperationEnum: "Approve" | "Deny" | "Block";
        JoinRoomOperation: {
            /** @description RoomId */
            Room: string;
            UserId: string;
            Operation: components["schemas"]["JoinRoomOperationEnum"];
        };
        RoomMember: {
            UserId: string;
            Role: string;
        };
        /** @enum {string} */
        RoomMemberOperationEnum: "Add" | "Delete" | "Update";
        RoomMemberOperation: {
            Operation: components["schemas"]["RoomMemberOperationEnum"];
            Member: components["schemas"]["RoomMember"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
