/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        NotificationType: "NewMessage" | "NewRoom" | "UpdateMessage" | "AddContact";
        Notification: {
            NotificationType: components["schemas"]["NotificationType"];
            Body: components["schemas"]["NewMessageNotificationBody"] | components["schemas"]["NewRoomNotificationBody"] | components["schemas"]["UpdateMessageNotificationBody"] | components["schemas"]["AddContactNotificationBody"];
        };
        NewMessageNotificationBody: {
            Conversation: components["schemas"]["ChatConversation"];
            Message: components["schemas"]["MessageInfo"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            NotificationType: "NewMessage";
        };
        NewMessageNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            NotificationType?: "NewMessage";
        };
        NewRoomNotificationBody: {
            RoomId: string;
            Title: string;
            DefaultConversationId?: string;
            /** @description null for now */
            Properties?: Record<string, never> | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            NotificationType: "NewRoom";
        };
        NewRoomNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            NotificationType?: "NewRoom";
            Body?: components["schemas"]["NewRoomNotificationBody"];
        };
        UpdateMessageNotificationBody: {
            Conversation: components["schemas"]["ChatConversation"];
            Message: components["schemas"]["MessageInfo"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            NotificationType: "UpdateMessage";
        };
        UpdateMessageNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            NotificationType?: "UpdateMessage";
            Body?: components["schemas"]["UpdateMessageNotificationBody"];
        };
        AddContactNotificationBody: {
            UserId: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            NotificationType: "AddContact";
        };
        AddContactNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            NotificationType?: "AddContact";
            Body?: components["schemas"]["AddContactNotificationBody"];
        };
        UserProfile: {
            /**
             * @description Unique identifier for the user
             * @example user123
             */
            UserId: string;
            /**
             * @description Array of room IDs the user is in
             * @example [
             *       "room1",
             *       "room2",
             *       "room3"
             *     ]
             */
            RoomIds?: string[];
            /**
             * @description Array of conversation IDs the user is in
             * @example [
             *       "id1",
             *       "id2",
             *       "id3"
             *     ]
             */
            ConversationIds?: string[];
        };
        ListUserConversationRequest: {
            ContinuationToken?: string | null;
            /** @default 1000 */
            MaxCount: number | null;
        };
        ListUserConversationResponse: {
            Conversations: components["schemas"]["ChatConversation"][];
            ContinuationToken?: string | null;
        };
        ChatConversation: {
            RoomId?: string | null;
            /** @description null for now */
            TopicId?: string | null;
            ConversationId?: string | null;
        };
        /** @enum {string} */
        ApprovalEnum: "AutoApprove" | "ManualApprove" | "AutoDeny";
        UserPolicy: {
            AddContact: components["schemas"]["ApprovalEnum"];
            /**
             * @example [
             *       "Nickname"
             *     ]
             */
            PublicProperties?: string[];
            FriendProperties?: string[];
            PrivateProperties?: string[];
        };
        /** @enum {string} */
        ContactResultState: "OK" | "Pending" | "Failed";
        AddContactResult: {
            UserId: string;
            State: components["schemas"]["ContactResultState"];
            Message: string;
        };
        ContactRequest: {
            UserId: string;
            Message: string;
        };
        /** @enum {string} */
        ContactOperation: "Approve" | "Deny" | "Block";
        ContactRequestOperation: {
            Operation: components["schemas"]["ContactOperation"];
            UserId: string;
        };
        RoomInfo: {
            RoomId: string;
            Title: string;
            DefaultConversationId: string;
            /** @description null for now */
            Properties?: Record<string, never> | null;
        };
        RoomInfoWithMembers: components["schemas"]["RoomInfo"] & {
            /** @description List of user id */
            Members: string[];
        };
        /** @enum {string} */
        RoomMemberJoinEnum: "AutoApprove" | "ManualApprove" | "InviteOnly";
        /** @enum {string} */
        RoomMessagePermissionEnum: "Allow" | "AdminOnly" | "Deny";
        /** @enum {string} */
        RoomReactPermissionEnum: "Allow" | "Deny";
        RoomPolicy: {
            MemberJoin: components["schemas"]["RoomMemberJoinEnum"];
            "MessageType.Text"?: components["schemas"]["RoomMessagePermissionEnum"];
            "MessageType.Image"?: components["schemas"]["RoomMessagePermissionEnum"];
            React?: components["schemas"]["RoomReactPermissionEnum"];
        };
        MessageRangeQuery: {
            Conversation: components["schemas"]["ChatConversation"];
            /** @description MessageId */
            Start?: string | null;
            /** @description MessageId */
            End?: string | null;
            /** @default 100 */
            MaxCount: number | null;
        };
        MessageInfo: {
            MessageId: string;
            /** @description UserId */
            CreatedBy?: string;
            /** Format: date-time */
            CreatedAt?: string;
            /** @example Join/Leave/Text/Emoji/File/Image/Voice/... */
            BodyType?: string;
            /** @example Inline/Reference/External/... */
            MessageBodyType: string;
            Body: string;
            RefMessageId?: string | null;
        };
        CreateTextMessage: {
            Conversation: components["schemas"]["ChatConversation"];
            Message: string;
            RefMessageId?: string | null;
            /** @description Array of UserId */
            "Ext.Mentions"?: string[] | null;
            "Ext.DeleteAfterRead"?: boolean | null;
            /** Format: date-time */
            "Ext.Scheduled"?: string | null;
        };
        CreateMessage: {
            Conversation: components["schemas"]["ChatConversation"];
            /** @example Text/Emoji/File/Image/Voice/... */
            MessageType: string;
            /** Format: binary */
            Body: string;
            RefMessageId?: string | null;
            /** @description Array of UserId */
            "Ext.Mentions"?: string[] | null;
            "Ext.DeleteAfterRead"?: boolean | null;
            /** Format: date-time */
            "Ext.Scheduled"?: string | null;
        };
        MessageBody: {
            Conversation: components["schemas"]["ChatConversation"];
            MessageId: string;
            /** @example Join/Leave/Text/Emoji/File/Image/Voice/... */
            MessageType: string;
            /** @example Inline/Reference/External/... */
            MessageBodyType: string;
            /** Format: binary */
            Body: string;
            RefMessageId?: string | null;
        };
        /** @enum {string} */
        JoinRoomState: "OK" | "Pending" | "Failed";
        JoinRoomResult: {
            /** @description RoomId */
            Room: string;
            State: components["schemas"]["JoinRoomState"];
            Message: string;
        };
        JoinRoomRequest: {
            UserId: string;
            Message: string;
        };
        /** @enum {string} */
        JoinRoomOperationEnum: "Approve" | "Deny" | "Block";
        JoinRoomOperation: {
            /** @description RoomId */
            Room: string;
            UserId: string;
            Operation: components["schemas"]["JoinRoomOperationEnum"];
        };
        RoomMember: {
            UserId: string;
            Role: string;
        };
        /** @enum {string} */
        RoomMemberOperationEnum: "Add" | "Delete" | "Update";
        RoomMemberOperation: {
            Operation: components["schemas"]["RoomMemberOperationEnum"];
            Member: components["schemas"]["RoomMember"];
        };
        SendMessageResponse: {
            Id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

// Flattened schema exports
export type Schemas = components["schemas"];
export type NotificationType = Schemas["NotificationType"];
export type Notification = Schemas["Notification"];
export type NewMessageNotificationBody = Schemas["NewMessageNotificationBody"];
export type NewMessageNotification = Schemas["NewMessageNotification"];
export type NewRoomNotificationBody = Schemas["NewRoomNotificationBody"];
export type NewRoomNotification = Schemas["NewRoomNotification"];
export type UpdateMessageNotificationBody = Schemas["UpdateMessageNotificationBody"];
export type UpdateMessageNotification = Schemas["UpdateMessageNotification"];
export type AddContactNotificationBody = Schemas["AddContactNotificationBody"];
export type AddContactNotification = Schemas["AddContactNotification"];
export type UserProfile = Schemas["UserProfile"];
export type ListUserConversationRequest = Schemas["ListUserConversationRequest"];
export type ListUserConversationResponse = Schemas["ListUserConversationResponse"];
export type ChatConversation = Schemas["ChatConversation"];
export type ApprovalEnum = Schemas["ApprovalEnum"];
export type UserPolicy = Schemas["UserPolicy"];
export type ContactResultState = Schemas["ContactResultState"];
export type AddContactResult = Schemas["AddContactResult"];
export type ContactRequest = Schemas["ContactRequest"];
export type ContactOperation = Schemas["ContactOperation"];
export type ContactRequestOperation = Schemas["ContactRequestOperation"];
export type RoomInfo = Schemas["RoomInfo"];
export type RoomInfoWithMembers = Schemas["RoomInfoWithMembers"];
export type RoomMemberJoinEnum = Schemas["RoomMemberJoinEnum"];
export type RoomMessagePermissionEnum = Schemas["RoomMessagePermissionEnum"];
export type RoomReactPermissionEnum = Schemas["RoomReactPermissionEnum"];
export type RoomPolicy = Schemas["RoomPolicy"];
export type MessageRangeQuery = Schemas["MessageRangeQuery"];
export type MessageInfo = Schemas["MessageInfo"];
export type CreateTextMessage = Schemas["CreateTextMessage"];
export type CreateMessage = Schemas["CreateMessage"];
export type MessageBody = Schemas["MessageBody"];
export type JoinRoomState = Schemas["JoinRoomState"];
export type JoinRoomResult = Schemas["JoinRoomResult"];
export type JoinRoomRequest = Schemas["JoinRoomRequest"];
export type JoinRoomOperationEnum = Schemas["JoinRoomOperationEnum"];
export type JoinRoomOperation = Schemas["JoinRoomOperation"];
export type RoomMember = Schemas["RoomMember"];
export type RoomMemberOperationEnum = Schemas["RoomMemberOperationEnum"];
export type RoomMemberOperation = Schemas["RoomMemberOperation"];
export type SendMessageResponse = Schemas["SendMessageResponse"];
