/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        NotificationType: "NewMessage" | "NewRoom" | "UpdateMessage" | "AddContact" | "MemberJoined";
        Notification: {
            notificationType: components["schemas"]["NotificationType"];
            body: components["schemas"]["NewMessageNotificationBody"] | components["schemas"]["NewRoomNotificationBody"] | components["schemas"]["UpdateMessageNotificationBody"] | components["schemas"]["AddContactNotificationBody"] | components["schemas"]["MemberJoinedNotificationBody"];
        };
        NewMessageNotificationBody: {
            conversation: components["schemas"]["ChatConversation"];
            message: components["schemas"]["MessageInfo"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            notificationType: "NewMessage";
        };
        NewMessageNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            notificationType?: "NewMessage";
        };
        NewRoomNotificationBody: {
            roomId: string;
            title: string;
            defaultConversationId?: string;
            /** @description null for now */
            properties?: Record<string, never> | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            notificationType: "NewRoom";
        };
        NewRoomNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            notificationType?: "NewRoom";
            body?: components["schemas"]["NewRoomNotificationBody"];
        };
        UpdateMessageNotificationBody: {
            conversation: components["schemas"]["ChatConversation"];
            message: components["schemas"]["MessageInfo"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            notificationType: "UpdateMessage";
        };
        UpdateMessageNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            notificationType?: "UpdateMessage";
            body?: components["schemas"]["UpdateMessageNotificationBody"];
        };
        AddContactNotificationBody: {
            userId: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            notificationType: "AddContact";
        };
        AddContactNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            notificationType?: "AddContact";
            body?: components["schemas"]["AddContactNotificationBody"];
        };
        MemberJoinedNotificationBody: {
            roomId: string;
            title: string;
            userId: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            notificationType: "MemberJoined";
        };
        MemberJoinedNotification: components["schemas"]["Notification"] & {
            /** @enum {string} */
            notificationType?: "MemberJoined";
            body?: components["schemas"]["MemberJoinedNotificationBody"];
        };
        UserProfile: {
            /**
             * @description Unique identifier for the user
             * @example user123
             */
            userId: string;
            /**
             * @description Array of room IDs the user is in
             * @example [
             *       "room1",
             *       "room2",
             *       "room3"
             *     ]
             */
            roomIds?: string[];
            /**
             * @description Array of conversation IDs the user is in
             * @example [
             *       "id1",
             *       "id2",
             *       "id3"
             *     ]
             */
            conversationIds?: string[];
        };
        ListUserConversationRequest: {
            continuationToken?: string | null;
            /** @default 1000 */
            maxCount: number | null;
        };
        ListUserConversationResponse: {
            conversations: components["schemas"]["ChatConversation"][];
            continuationToken?: string | null;
        };
        ChatConversation: {
            roomId?: string | null;
            /** @description null for now */
            topicId?: string | null;
            conversationId?: string | null;
        };
        /** @enum {string} */
        ApprovalEnum: "AutoApprove" | "ManualApprove" | "AutoDeny";
        UserPolicy: {
            addContact: components["schemas"]["ApprovalEnum"];
            /**
             * @example [
             *       "Nickname"
             *     ]
             */
            publicProperties?: string[];
            friendProperties?: string[];
            privateProperties?: string[];
        };
        /** @enum {string} */
        ContactResultState: "OK" | "Pending" | "Failed";
        AddContactResult: {
            userId: string;
            state: components["schemas"]["ContactResultState"];
            message: string;
        };
        ContactRequest: {
            userId: string;
            message: string;
        };
        /** @enum {string} */
        ContactOperation: "Approve" | "Deny" | "Block";
        ContactRequestOperation: {
            operation: components["schemas"]["ContactOperation"];
            userId: string;
        };
        RoomInfo: {
            roomId: string;
            title: string;
            defaultConversationId: string;
            /** @description null for now */
            properties?: Record<string, never> | null;
        };
        RoomInfoWithMembers: components["schemas"]["RoomInfo"] & {
            /** @description List of user id */
            members: string[];
        };
        /** @enum {string} */
        RoomMemberJoinEnum: "AutoApprove" | "ManualApprove" | "InviteOnly";
        /** @enum {string} */
        RoomMessagePermissionEnum: "Allow" | "AdminOnly" | "Deny";
        /** @enum {string} */
        RoomReactPermissionEnum: "Allow" | "Deny";
        RoomPolicy: {
            memberJoin: components["schemas"]["RoomMemberJoinEnum"];
            messageTypeText?: components["schemas"]["RoomMessagePermissionEnum"];
            messageTypeImage?: components["schemas"]["RoomMessagePermissionEnum"];
            react?: components["schemas"]["RoomReactPermissionEnum"];
        };
        MessageRangeQuery: {
            conversation: components["schemas"]["ChatConversation"];
            /** @description MessageId */
            start?: string | null;
            /** @description MessageId */
            end?: string | null;
            /** @default 100 */
            maxCount: number | null;
        };
        MessageInfo: {
            messageId: string;
            /** @description UserId */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** @example Join/Leave/Text/Emoji/File/Image/Voice/... */
            bodyType?: string;
            /** @example Inline/Reference/External/... */
            messageBodyType: string;
            content: {
                text?: string | null;
                /** Format: binary */
                binary?: string | null;
            };
            refMessageId?: string | null;
        };
        CreateTextMessage: {
            conversation: components["schemas"]["ChatConversation"];
            message: string;
            refMessageId?: string | null;
            /** @description Array of UserId */
            extMentions?: string[] | null;
            extDeleteAfterRead?: boolean | null;
            /** Format: date-time */
            extScheduled?: string | null;
        };
        CreateMessage: {
            conversation: components["schemas"]["ChatConversation"];
            /** @example Text/Emoji/File/Image/Voice/... */
            messageType: string;
            content: {
                text?: string | null;
                /** Format: binary */
                binary?: string | null;
            };
            refMessageId?: string | null;
            /** @description Array of UserId */
            extMentions?: string[] | null;
            extDeleteAfterRead?: boolean | null;
            /** Format: date-time */
            extScheduled?: string | null;
        };
        MessageBody: {
            conversation: components["schemas"]["ChatConversation"];
            messageId: string;
            /** @example Join/Leave/Text/Emoji/File/Image/Voice/... */
            messageType: string;
            /** @example Inline/Reference/External/... */
            messageBodyType: string;
            content: {
                text?: string | null;
                /** Format: binary */
                binary?: string | null;
            };
            refMessageId?: string | null;
        };
        /** @enum {string} */
        JoinRoomState: "OK" | "Pending" | "Failed";
        JoinRoomResult: {
            /** @description RoomId */
            room: string;
            state: components["schemas"]["JoinRoomState"];
            message: string;
        };
        JoinRoomRequest: {
            userId: string;
            message: string;
        };
        /** @enum {string} */
        JoinRoomOperationEnum: "Approve" | "Deny" | "Block";
        JoinRoomOperation: {
            /** @description RoomId */
            room: string;
            userId: string;
            operation: components["schemas"]["JoinRoomOperationEnum"];
        };
        RoomMember: {
            userId: string;
            role: string;
        };
        /** @enum {string} */
        RoomMemberOperationEnum: "Add" | "Delete" | "Update";
        RoomMemberOperation: {
            operation: components["schemas"]["RoomMemberOperationEnum"];
            member: components["schemas"]["RoomMember"];
        };
        /** @enum {string} */
        RoomMemberOperationType: "Add" | "Delete";
        ManageRoomMemberRequest: {
            roomId: string;
            operation: components["schemas"]["RoomMemberOperationType"];
            userId: string;
        };
        SendMessageResponse: {
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;

// Flattened schema exports
export type Schemas = components["schemas"];
export type NotificationType = Schemas["NotificationType"];
export type Notification = Schemas["Notification"];
export type NewMessageNotificationBody = Schemas["NewMessageNotificationBody"];
export type NewMessageNotification = Schemas["NewMessageNotification"];
export type NewRoomNotificationBody = Schemas["NewRoomNotificationBody"];
export type NewRoomNotification = Schemas["NewRoomNotification"];
export type UpdateMessageNotificationBody = Schemas["UpdateMessageNotificationBody"];
export type UpdateMessageNotification = Schemas["UpdateMessageNotification"];
export type AddContactNotificationBody = Schemas["AddContactNotificationBody"];
export type AddContactNotification = Schemas["AddContactNotification"];
export type MemberJoinedNotificationBody = Schemas["MemberJoinedNotificationBody"];
export type MemberJoinedNotification = Schemas["MemberJoinedNotification"];
export type UserProfile = Schemas["UserProfile"];
export type ListUserConversationRequest = Schemas["ListUserConversationRequest"];
export type ListUserConversationResponse = Schemas["ListUserConversationResponse"];
export type ChatConversation = Schemas["ChatConversation"];
export type ApprovalEnum = Schemas["ApprovalEnum"];
export type UserPolicy = Schemas["UserPolicy"];
export type ContactResultState = Schemas["ContactResultState"];
export type AddContactResult = Schemas["AddContactResult"];
export type ContactRequest = Schemas["ContactRequest"];
export type ContactOperation = Schemas["ContactOperation"];
export type ContactRequestOperation = Schemas["ContactRequestOperation"];
export type RoomInfo = Schemas["RoomInfo"];
export type RoomInfoWithMembers = Schemas["RoomInfoWithMembers"];
export type RoomMemberJoinEnum = Schemas["RoomMemberJoinEnum"];
export type RoomMessagePermissionEnum = Schemas["RoomMessagePermissionEnum"];
export type RoomReactPermissionEnum = Schemas["RoomReactPermissionEnum"];
export type RoomPolicy = Schemas["RoomPolicy"];
export type MessageRangeQuery = Schemas["MessageRangeQuery"];
export type MessageInfo = Schemas["MessageInfo"];
export type CreateTextMessage = Schemas["CreateTextMessage"];
export type CreateMessage = Schemas["CreateMessage"];
export type MessageBody = Schemas["MessageBody"];
export type JoinRoomState = Schemas["JoinRoomState"];
export type JoinRoomResult = Schemas["JoinRoomResult"];
export type JoinRoomRequest = Schemas["JoinRoomRequest"];
export type JoinRoomOperationEnum = Schemas["JoinRoomOperationEnum"];
export type JoinRoomOperation = Schemas["JoinRoomOperation"];
export type RoomMember = Schemas["RoomMember"];
export type RoomMemberOperationEnum = Schemas["RoomMemberOperationEnum"];
export type RoomMemberOperation = Schemas["RoomMemberOperation"];
export type RoomMemberOperationType = Schemas["RoomMemberOperationType"];
export type ManageRoomMemberRequest = Schemas["ManageRoomMemberRequest"];
export type SendMessageResponse = Schemas["SendMessageResponse"];
