FROM node:26-alpine AS node-builder

WORKDIR /app

# Install app dependencies
COPY package.json .
RUN npm install

# Bundle app source
COPY . .

RUN npm run build

FROM nginx:1.31.4

WORKDIR /usr/share/nginx/html

COPY --from=node-builder /app/dist .
