// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

package openapi

import (
	"context"
	"net/http"
)



// DefaultAPIRouter defines the required methods for binding the api requests to a responses for the DefaultAPI
// The DefaultAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultAPIServicer to perform the required actions, then write the service results to the http response.
type DefaultAPIRouter interface { 
	OnMqttClientConnected(http.ResponseWriter, *http.Request)
	OnMqttClientDisconnected(http.ResponseWriter, *http.Request)
	OnMqttConnect(http.ResponseWriter, *http.Request)
}


// DefaultAPIServicer defines the api actions for the DefaultAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultAPIServicer interface { 
	OnMqttClientConnected(context.Context, string, string, string, string, map[string]interface{}, string, string, string, string) (ImplResponse, error)
	OnMqttClientDisconnected(context.Context, string, string, string, string, MqttDisconnectedEventRequest, string, string, string, string) (ImplResponse, error)
	OnMqttConnect(context.Context, string, string, string, string, MqttConnectEventRequest, string, string, string, string) (ImplResponse, error)
}
