// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

package openapi




// MqttConnectEventFailureResponse - Represents the response properties of an MQTT connection failure.
type MqttConnectEventFailureResponse struct {

	Mqtt MqttConnectEventFailureResponseProperties `json:"mqtt"`
}

// AssertMqttConnectEventFailureResponseRequired checks if the required fields are not zero-ed
func AssertMqttConnectEventFailureResponseRequired(obj MqttConnectEventFailureResponse) error {
	elements := map[string]interface{}{
		"mqtt": obj.Mqtt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertMqttConnectEventFailureResponsePropertiesRequired(obj.Mqtt); err != nil {
		return err
	}
	return nil
}

// AssertMqttConnectEventFailureResponseConstraints checks if the values respects the defined constraints
func AssertMqttConnectEventFailureResponseConstraints(obj MqttConnectEventFailureResponse) error {
	if err := AssertMqttConnectEventFailureResponsePropertiesConstraints(obj.Mqtt); err != nil {
		return err
	}
	return nil
}
