// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

package openapi




// MqttUserProperty - Represents a user property in an MQTT connection.
type MqttUserProperty struct {

	Name string `json:"name"`

	Value string `json:"value"`
}

// AssertMqttUserPropertyRequired checks if the required fields are not zero-ed
func AssertMqttUserPropertyRequired(obj MqttUserProperty) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"value": obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertMqttUserPropertyConstraints checks if the values respects the defined constraints
func AssertMqttUserPropertyConstraints(obj MqttUserProperty) error {
	return nil
}
