// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

package openapi




// MqttConnectEventRequest - Represents a request for an MQTT connection event.
type MqttConnectEventRequest struct {

	Mqtt MqttConnectEventProperties `json:"mqtt"`

	Claims map[string][]string `json:"claims"`

	Query map[string][]string `json:"query"`

	Headers map[string][]string `json:"headers"`

	Subprotocols []string `json:"subprotocols"`

	ClientCertificates []ClientCertificateInfo `json:"clientCertificates"`
}

// AssertMqttConnectEventRequestRequired checks if the required fields are not zero-ed
func AssertMqttConnectEventRequestRequired(obj MqttConnectEventRequest) error {
	elements := map[string]interface{}{
		"mqtt": obj.Mqtt,
		"claims": obj.Claims,
		"query": obj.Query,
		"headers": obj.Headers,
		"subprotocols": obj.Subprotocols,
		"clientCertificates": obj.ClientCertificates,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertMqttConnectEventPropertiesRequired(obj.Mqtt); err != nil {
		return err
	}
	for _, el := range obj.ClientCertificates {
		if err := AssertClientCertificateInfoRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertMqttConnectEventRequestConstraints checks if the values respects the defined constraints
func AssertMqttConnectEventRequestConstraints(obj MqttConnectEventRequest) error {
	if err := AssertMqttConnectEventPropertiesConstraints(obj.Mqtt); err != nil {
		return err
	}
	for _, el := range obj.ClientCertificates {
		if err := AssertClientCertificateInfoConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
