// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

package openapi




// MqttDisconnectedEventRequest - Represents a request for an MQTT disconnection event.
type MqttDisconnectedEventRequest struct {

	Mqtt MqttDisconnectedEventProperties `json:"mqtt"`

	Reason string `json:"reason"`
}

// AssertMqttDisconnectedEventRequestRequired checks if the required fields are not zero-ed
func AssertMqttDisconnectedEventRequestRequired(obj MqttDisconnectedEventRequest) error {
	elements := map[string]interface{}{
		"mqtt": obj.Mqtt,
		"reason": obj.Reason,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertMqttDisconnectedEventPropertiesRequired(obj.Mqtt); err != nil {
		return err
	}
	return nil
}

// AssertMqttDisconnectedEventRequestConstraints checks if the values respects the defined constraints
func AssertMqttDisconnectedEventRequestConstraints(obj MqttDisconnectedEventRequest) error {
	if err := AssertMqttDisconnectedEventPropertiesConstraints(obj.Mqtt); err != nil {
		return err
	}
	return nil
}
