// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 */

package openapi

type ClientCertificateInfo struct {

	Thumbprint string `json:"thumbprint"`

	Content string `json:"content"`
}

// AssertClientCertificateInfoRequired checks if the required fields are not zero-ed
func AssertClientCertificateInfoRequired(obj ClientCertificateInfo) error {
	elements := map[string]interface{}{
		"thumbprint": obj.Thumbprint,
		"content": obj.Content,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertClientCertificateInfoConstraints checks if the values respects the defined constraints
func AssertClientCertificateInfoConstraints(obj ClientCertificateInfo) error {
	return nil
}
