# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'tests/integration-tests/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'tests/integration-tests/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        dotnet-version: [6.x]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Test VSCode Extension
      # See https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
      run:  cd ./tools/vscode-azurewebpubsub && npm install && xvfb-run -a npm run test && cd ../../
      if: runner.os == 'Linux'
    - run: npm install -g yarn
    - run: yarn install
    - run: |
        cd tools/awps-tunnel/client
        yarn install
        yarn test
    - run: yarn workspaces run test
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Build C# samples
      run: dotnet build samples/csharp/samples.sln

