# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Integration tests for C#

on:
  workflow_dispatch:
    inputs:
      web_pubsub_connection_string:
        description: 'Azure Web PubSub Connection String'
        required: true
        type: string
  push:
    branches: [ "main" ]
    paths:
      - 'tests/integration-tests/csharp/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'tests/integration-tests/csharp/**'

jobs:
  test:
    name: Integration tests for C#
    runs-on: ubuntu-latest
    env:
      WEB_PUBSUB_CONNECTION_STRING: ${{ github.event.inputs.web_pubsub_connection_string || secrets.WEB_PUBSUB_CONNECTION_STRING }}
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        dotnet-version: [8.x]
    steps:
    - uses: actions/checkout@v4
    - name: Test csharp tests
      run: dotnet test tests/integration-tests/csharp/csharp.csproj

