# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Integration tests for Java

on:
  workflow_dispatch:
    inputs:
      web_pubsub_connection_string:
        description: 'Azure Web PubSub Connection String'
        required: true
        type: string
  push:
    branches: [ "main" ]
    paths:
      - 'tests/integration-tests/java/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'tests/integration-tests/java/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WEB_PUBSUB_CONNECTION_STRING: ${{ github.event.inputs.web_pubsub_connection_string || secrets.WEB_PUBSUB_CONNECTION_STRING }}
    strategy:
      matrix:
        java-version: [17]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Build and test with Maven
      run: |
        cd tests/integration-tests/java/integration-tests
        mvn -B verify --file pom.xml