# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        dotnet-version: [6.x]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g yarn 
    - run: yarn install
    - run: yarn workspaces run test
    - name: socketio
      run: |
        pushd experimental/sdk/webpubsub-socketio-extension
        yarn build
        yarn pack
        for file in $(find . -type f -name '*.tgz'); do
          path = "./experimental/sdk/webpubsub-socketio-extension/${file#./}
          echo "File found: $path"
          echo "::set-output name=artifacts::$path"
        done
        popd
      shell: bash
    - name: Publish SocketIO Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: socketio package
        path: ${{ steps.socketio.outputs.artifacts }}    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Build C# projects
      run: dotnet build samples/csharp/samples.sln
