name: Release tunnel package
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    paths:
      - 'tools/awps-tunnel/server/package.json'
jobs:
  version_check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read_current_version.outputs.current_version }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Read current version from package.json
      id: read_current_version
      run:  |
        current_version=$(jq -r '.version' tools/awps-tunnel/server/package.json)
        echo "Current version: $current_version"
        echo "current_version=$current_version" >> $GITHUB_OUTPUT
    - name: Validate version in change log #Changelog should contain the matching description
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: error
        version: ${{ steps.read_current_version.outputs.current_version }}
        path: tools/awps-tunnel/server/CHANGELOG.md
    - name: Extract version from tag
      id: tag_version
      run: |
        TAG_NAME="${GITHUB_REF#refs/tags/}"  # Extract tag name from GITHUB_REF
        VERSION=$(echo "$TAG_NAME" | sed -n 's|^release/awps-tunnel/v\(.*\)$|\1|p')
        echo "tag_version=$VERSION" >> $GITHUB_OUTPUT
    - name: Compare versions
      id: compare_versions
      run: |
        if [[ "${{ steps.tag_version.outputs.tag_version }}" != "${{ steps.read_current_version.outputs.current_version }}" ]]; then
          echo "Version changed. Running the workflow..."
          echo "version_changed=true" >> $GITHUB_OUTPUT
        else
          echo "Version not changed. Skipping the workflow..."
          echo "version_changed=false" >> $GITHUB_OUTPUT
        fi
    - name: Run release workflow
      if: steps.compare_versions.outputs.version_changed == 'true'
      uses: build-tunnel.yml
      with:
        version: ${{ steps.read_current_version.outputs.current_version }}