name: Release Azure SocketIO package
on:
  push:
    branches: [ "main" ]
    paths:
      - 'sdk/webpubsub-socketio-extension/package.json'

env:
  NODE_VERSION: '18.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 3

    - name: Get previous version of package.json from git
      id: get_previous_version
      run: |
        git log -3
        previous_hash=$(git log -n 3 --pretty=format:'%H' | tail -n 1)
        previous_version=$(git show $previous_hash:sdk/webpubsub-socketio-extension/package.json | jq -r '.version')
        echo "Previous version: $previous_version"
        echo "previous_version=$previous_version" >> $GITHUB_OUTPUT

    - name: Read current version from package.json
      id: read_current_version
      run:  |
        current_version=$(jq -r '.version' sdk/webpubsub-socketio-extension/package.json)
        echo "Current version: $current_version"
        echo "current_version=$current_version" >> $GITHUB_OUTPUT

    - name: Compare versions
      id: compare_versions
      run: |
        if [[ "${{ steps.get_previous_version.outputs.previous_version }}" != "${{ steps.read_current_version.outputs.current_version }}" ]]; then
          echo "Version changed. Running the workflow..."
          echo "version_changed=true" >> $GITHUB_OUTPUT
        else
          echo "Version not changed. Skipping the workflow..."
          echo "version_changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
      if: steps.compare_versions.outputs.version_changed == 'true'

    - name: Install dependencies
      run: npm install -g yarn 
      if: steps.compare_versions.outputs.version_changed == 'true'

    - name: Pack SocketIO package
      id: socketio
      if: steps.compare_versions.outputs.version_changed == 'true'
      run: |
        pushd sdk/server-proxies
        yarn
        popd
        pushd sdk/webpubsub-socketio-extension
        yarn
        yarn build
        yarn pack
        for file in $(find . -type f -name '*.tgz'); do
          path="./sdk/webpubsub-socketio-extension/${file#./}"
          echo "packageName=${file#./}" >> $GITHUB_OUTPUT
          echo "packagePath=$path" >> $GITHUB_OUTPUT
        done
        popd
      shell: bash
    - name: AzCopy to shared blob
      if: steps.compare_versions.outputs.version_changed == 'true'
      env:
        URL: ${{ secrets.AZURESDKPARTNERDROPS_URL }}
        AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZURESDKPARTNERDROPS_SERVICE_PRINCIPAL_KEY }}
        ID: ${{ secrets.AZURESDKPARTNERDROPS_SERVICE_PRINCIPAL_ID }}
        TENENT: ${{ secrets.AZURESDKPARTNERDROPS_TENANT_ID }}
        BUILDNUMBER: ${{ steps.read_current_version.outputs.current_version }}
      run: |
        azcopy login --service-principal --application-id $ID --tenent-id $TENENT
        azcopy copy ${{ steps.socketio.outputs.packagePath }} "$URL/azure-webpubsub/js/$BUILDNUMBER/"
    - name: Publish SocketIO Artifacts
      if: steps.compare_versions.outputs.version_changed == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: socketio package
        path: ${{ steps.socketio.outputs.packagePath }} 
