name: Release Azure SocketIO package
permissions:
  id-token: write # This is required for requesting the JWT
on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/release_socketio.yml'
      - 'sdk/webpubsub-socketio-extension/package.json'
      - 'sdk/webpubsub-socketio-extension/CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/workflow-call-release-package.yml
    secrets:
      AZURESDKPARTNERDROPS_URL: ${{ secrets.AZURESDKPARTNERDROPS_URL }}
      AZURESDKPARTNERDROPS_CLIENT_ID: ${{ secrets.AZURESDKPARTNERDROPS_CLIENT_ID }}
      AZURESDKPARTNERDROPS_SUBSCRIPTION_ID: ${{ secrets.AZURESDKPARTNERDROPS_SUBSCRIPTION_ID }}
      AZURESDKPARTNERDROPS_TENANT_ID: ${{ secrets.AZURESDKPARTNERDROPS_TENANT_ID }}
    with:
      package_name: webpubsub-socketio-extension
      package_folder: sdk/webpubsub-socketio-extension
