name: Release tunnel package
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/release_tunnel.yml'
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/release_tunnel.yml'
      - 'tools/awps-tunnel/server/package.json'
      - 'tools/awps-tunnel/server/CHANGELOG.md'
jobs: 
  release:
    uses: ./.github/workflows/workflow-call-release-package.yml
    secrets:
      AZURESDKPARTNERDROPS_URL: ${{ secrets.AZURESDKPARTNERDROPS_URL }}
      AZURESDKPARTNERDROPS_CLIENT_ID: ${{ secrets.AZURESDKPARTNERDROPS_CLIENT_ID }}
      AZURESDKPARTNERDROPS_SUBSCRIPTION_ID: ${{ secrets.AZURESDKPARTNERDROPS_SUBSCRIPTION_ID }}
      AZURESDKPARTNERDROPS_TENANT_ID: ${{ secrets.AZURESDKPARTNERDROPS_TENANT_ID }}
      GH_PAT: ${{ secrets.GH_PAT }}
    with:
      package_name: awps-tunnel
      package_folder: tools/awps-tunnel/server