name: Release tunnel package
on:
  push:
    branches: [ "main" ]
    paths:
      - 'tools/awps-tunnel/server/package.json'
      - 'tools/awps-tunnel/server/CHANGELOG.md'

env:
  NODE_VERSION: '18.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Changelog new version to release
    id: changelog_reader
    uses: mindsers/changelog-reader-action@v2
    with:
      validation_level: error
      version: ${{ steps.read_current_version.outputs.current_version }}
      path: tools/awps-tunnel/server/CHANGELOG.md

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
      if: steps.compare_versions.outputs.version_changed == 'true'

    - name: Install dependencies
      run: npm install -g yarn 
      if: steps.compare_versions.outputs.version_changed == 'true'

    - name: Pack tunnel package
      id: tunnel
      if: steps.compare_versions.outputs.version_changed == 'true'
      run: |
        pushd sdk/server-proxies
        yarn
        popd
        pushd tools/awps-tunnel/client
        yarn
        popd
        pushd tools/awps-tunnel/server
        yarn
        yarn build
        yarn pack
        for file in $(find . -type f -name '*.tgz'); do
          path="./tools/awps-tunnel/server/${file#./}"
          echo "packageName=${file#./}" >> $GITHUB_OUTPUT
          echo "packagePath=$path" >> $GITHUB_OUTPUT
        done
        popd
      shell: bash
    - name: AzCopy to shared blob
      if: steps.compare_versions.outputs.version_changed == 'true'
      env:
        URL: ${{ secrets.AZURESDKPARTNERDROPS_URL }}
        AZCOPY_SPA_CLIENT_SECRET: ${{ secrets.AZURESDKPARTNERDROPS_SERVICE_PRINCIPAL_KEY }}
        ID: ${{ secrets.AZURESDKPARTNERDROPS_SERVICE_PRINCIPAL_ID }}
        TENANT: ${{ secrets.AZURESDKPARTNERDROPS_TENANT_ID }}
        BUILDNUMBER: ${{ steps.read_current_version.outputs.current_version }}
      run: |
        azcopy login --service-principal --application-id $ID --tenant-id $TENANT
        azcopy copy ${{ steps.tunnel.outputs.packagePath }} "$URL/azure-webpubsub/tunnel/$BUILDNUMBER/"
    - name: Publish tunnel Artifacts
      if: steps.compare_versions.outputs.version_changed == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: tunnel package
        path: ${{ steps.tunnel.outputs.packagePath }} 
