name: Release Socket.IO Admin UI

on: 
  push:
    branches:
      - main
    paths:
        - 'tools/azure-socketio-admin-ui/**'
  pull_request:
    branches:
      - main
    paths:
      - 'tools/azure-socketio-admin-ui/**'

permissions:
  contents: read

jobs:
  build_pack_upload:
    name: Release Socket.IO Admin UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/azure-socketio-admin-ui
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22

      - name: Build and Pack
        run:  yarn install && yarn build

      - name: Get Metadata
        id: metadata_step
        run: |
            package_version=$(node -p "require('./package.json').version")
            echo "package_version=${package_version}" >> $GITHUB_OUTPUT
            echo "filename=azure-socketio-admin-ui-${package_version}" >> $GITHUB_OUTPUT

      - name: Upload to Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
            name: ${{ steps.metadata_step.outputs.filename }}
            path: tools/azure-socketio-admin-ui/dist
