name: Validate changelogs # Check changelog formats following https://keepachangelog.com/en/1.1.0/
on:
  push:
    paths:
      - 'tools/awps-tunnel/server/package.json' # version in package.json should have an entry in changelog
      - 'tools/awps-tunnel/server/CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Read current version from package.json
      id: read_current_version
      run:  |
        current_version=$(jq -r '.version' tools/awps-tunnel/server/package.json)
        echo "Current version: $current_version"
        echo "current_version=$current_version" >> $GITHUB_OUTPUT
    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v2
      with:
        validation_level: error
        version: ${{ steps.read_current_version.outputs.current_version }}
        path: tools/awps-tunnel/server/CHANGELOG.md